{
 "title": "BDB Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(node_up,cluster)" },
   {
    "name": "bdb",
    "label": "BDB Id",
    "query": "label_values(bdb_conns{cluster=\"$cluster\"}, bdb)"
   },
   {
    "name": "status",
    "query": "label_values(bdb_status{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
   },
   {
    "name": "newStatus",
    "query": "label_values(bdb_up{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status for BDB:$bdb",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "content": "<b style=\"font-size: 20pt\">$status<b>\n<b style=\"font-size: 20pt\">$newStatus<b>"
  },
  {
   "title": "BDB:$bdb used memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(bdb_used_memory{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "BDB:$bdb #Keys",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(bdb_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "BDB:$bdb #Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(bdb_conns{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "BDB:$bdb #Listeners",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(listener_total_req{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "BDB:$bdb #Shards",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(redis_no_of_keys{cluster=\"$cluster\", bdb=\"$bdb\"}) or count(redis_used_memory{cluster=\"$cluster\", bdb=\"$bdb\"})"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Avg latency for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bdb_avg_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_latency"
    },
    {
     "expr": "bdb_avg_write_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_write_latency"
    },
    {
     "expr": "bdb_avg_read_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_read_latency"
    },
    {
     "expr": "bdb_avg_other_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_other_latency"
    },
    {
     "expr": "bdb_avg_latency_max{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_latency (max)"
    }
   ]
  },
  {
   "title": "Avg listener latency for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "listener_acc_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "listener {{proxy}}  node {{node}}"
    }
   ]
  },
  {
   "title": "Used Memory for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{bdb=\"$bdb\", cluster=\"$cluster\"}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "BDB:$bdb Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bdb_conns{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "listener_conns{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "listener: {{listener}} node: {{node}}"
    }
   ]
  },
  {
   "title": "CPU usage by shards for bdb:$bdb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb\",cluster=\"$cluster\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb\",cluster=\"$cluster\"}[60s]))/60*100 or redis_cpu_percent{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "shard: {{redis}} role: {{role}} node:{{node}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "# keys/shard",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"} or redis_db0_keys{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "redis #{{redis}}"
    }
   ]
  },
  {
   "title": "#Keys for BDB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "num of keys"
    },
    {
     "expr": "sum(redis_db0_expires{bdb=\"$bdb\", cluster=\"$cluster\"})",
     "legendFormat": "num of volatile keys"
    }
   ]
  },
  {
   "title": "Evicted objects for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_evicted_objects{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "BDB:$bdb"
    }
   ]
  },
  {
   "title": "Expired objects for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_expired_objects{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "BDB:$bdb"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Requests[total,read,write,other] for bdb:$bdb",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_total_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "total requests"
    },
    {
     "expr": "bdb_other_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "other requests"
    },
    {
     "expr": "bdb_read_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "read requests"
    },
    {
     "expr": "bdb_write_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "write requests"
    },
    {
     "expr": "bdb_total_req_max{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "total requests (max)"
    }
   ]
  },
  {
   "title": "BDB:$bdb Ingress/Egress",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "Bps", "label": "Ingress" }
   ],
   "targets": [
    {
     "expr": "bdb_egress_bytes{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "Egress"
    },
    {
     "expr": "bdb_ingress_bytes{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "Ingress"
    }
   ]
  },
  {
   "title": "Sizes of shards for bdb:$bdb",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Shard AOF Rewrites",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_rewrites{cluster=\"$cluster\", bdb=\"$bdb\"}[1m])",
     "legendFormat": "Redis {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_bigstore_io_reads{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "bdb_bigstore_io_writes{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "Writes"
    },
    {
     "expr": "bdb_bigstore_io_dels{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "IO Banwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_bigstore_io_read_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "bdb_bigstore_io_write_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "BDB sum redis wait busy key",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_wait_busy_key{bdb=\"$bdb\",cluster=\"$cluster\"}[1m]))",
     "legendFormat": "bdb:{{$bdb}}"
    }
   ]
  },
  {
   "title": "BDB main thread CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_main_thread_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "main threads"
    },
    {
     "expr": "bdb_shard_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_shard_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all threads"
    },
    {
     "expr": "bdb_fork_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_fork_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all forks"
    },
    {
     "expr": "bdb_main_thread_cpu_system_max{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_main_thread_cpu_user_max{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "main threads (max)"
    },
    {
     "expr": "bdb_shard_cpu_system_max{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_shard_cpu_user_max{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all threads (max)"
    }
   ]
  },
  {
   "title": "Shard RSS fragmentation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_fragmentation{bdb=\"$bdb\", cluster=\"$cluster\"} or redis_mem_fragmentation_ratio{bdb=\"$bdb\", cluster=\"$cluster\"} ",
     "legendFormat": "Redis {{redis}} ({{role}})"
    }
   ]
  }
 ]
}