{
 "title": "Node Dashboard",
 "tags": [ "RLEC" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(node_up,cluster)" },
   {
    "name": "node",
    "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "version",
    "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# BDBs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count_values(\"bdb\", redis_used_memory{cluster=\"$cluster\", node=\"$node\"}))"
    }
   ]
  },
  {
   "title": "# Shards",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(redis_used_memory{cluster=\"$cluster\", node=\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-node_cpu_idle{node=\"$node\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_available_memory{cluster=\"$cluster\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Node version",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "content": "<b style=\"font-size: 20pt\">$version<b>"
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage on node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "1- node_cpu_idle{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "CPU usage "
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Node $node In/Out Traffic",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "node_ingress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "Ingress for node {{node}}"
    },
    {
     "expr": "node_egress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "egress for node {{node}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Top 10 listeners Egress/Ingrees",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_egress_bytes{node=\"$node\", cluster=\"$cluster\"})",
     "legendFormat": "Egress listener {{listener}} for {{bdb}}"
    },
    {
     "expr": "topk(10, listener_ingress_bytes{node=\"$node\", cluster=\"$cluster\"})",
     "legendFormat": "Ingress listener {{listener}} for {{bdb}}"
    }
   ]
  },
  { "title": "BIGSTORE IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Top 10 shards by used memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, redis_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Top 10 active listeners by connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_conns{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "listener {{listener}} for  bdb {{bdb}}"
    }
   ]
  },
  {
   "title": "Top 10 active listeners by requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_total_req{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "listener {{listener}} for  bdb {{bdb}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "#Shards per BDB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(redis_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (bdb)",
     "legendFormat": "bdb:{{bdb}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_available_memory{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "available memory"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Size of shards on node (Ability for sorting like by size)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Shard's CPU on Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(redis_process_cpu_system_seconds_total{node=\"$node\",cluster=\"$cluster\"}[60s]) + delta(redis_process_cpu_user_seconds_total{node=\"$node\",cluster=\"$cluster\"}[60s]))/60*100",
     "legendFormat": "shard: {{redis}} role: {{role}} bdb: {{bdb}}"
    }
   ]
  },
  { "title": "ROF metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  { "title": "ROF metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "fork memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_last_cow_size{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard last RDB cow - redis: {{redis}}"
    },
    {
     "expr": "redis_aof_last_cow_size{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard last AOF cow - redis: {{redis}}"
    },
    {
     "expr": "redis_mem_aof_buffer{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard aofrw buffers - redis: {{redis}}"
    },
    {
     "expr": "redis_mem_clients_slaves{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard salve buffers - redis: {{redis}}"
    }
   ]
  }
 ]
}