{
 "title": "Cluster Dashboard",
 "tags": [ "RLEC" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(node_up,cluster)" },
   {
    "name": "node",
    "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(bdb_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(node_available_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Available"
    }
   ]
  },
  {
   "title": "Grow over 1min (Over 100MiB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(delta(bdb_used_memory{cluster=\"$cluster\"}[1m])) by (bdb) > 100 * 1024*1024",
     "legendFormat": "BDB #{{bdb}}"
    }
   ]
  },
  {
   "title": "Top 10 Requests by BDB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bdb_total_req{cluster=\"$cluster\"}) by (bdb) > 0)",
     "legendFormat": "#{{bdb}}"
    }
   ]
  },
  {
   "title": "CPU Usage for node $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_cpu_idle{cluster=\"$cluster\", node=\"$node\"}*100"
    }
   ]
  },
  {
   "title": "Top 10 Requests Per Listener",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_total_req{cluster=\"$cluster\"})",
     "legendFormat": "{{listener}} for bdb {{bdb}}"
    }
   ]
  },
  {
   "title": "Used Mem By redis for Node $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "node",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{node=\"$node\", cluster=\"$cluster\"}",
     "legendFormat": "BDB: {{bdb}} Redis: {{redis}}"
    }
   ]
  },
  {
   "title": "List of BDBs",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "bdb_used_memory{cluster=\"$cluster\"}",
     "legendFormat": "BDB {{bdb}}"
    }
   ]
  },
  {
   "title": "Used Mem By BDB over 30MB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{cluster=\"$cluster\"} > 30 * 1024 * 1024",
     "legendFormat": "BDB: {{bdb}} "
    }
   ]
  },
  {
   "title": "Top 10 Used conns By BDB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, bdb_conns{cluster=\"$cluster\"})",
     "legendFormat": "Conns for BDB: {{bdb}} "
    },
    {
     "expr": "topk(10, listener_conns{bdb=\"$bdb\", cluster=\"$cluster\"})",
     "legendFormat": "listener #{{listener}}"
    }
   ]
  }
 ]
}